export type MascotPose =
  | "NORMAL" | "SURPRESO" | "DESCONFIADO" | "BRAVO" | "RINDO" | "IRONICO" | "INDIGNADO"
  | "APONTANDO" | "APONTANDO_ESQUERDA" | "APONTANDO_DIREITA" | "APONTANDO_CIMA" | "APONTANDO_BAIXO"
  | "EXPLICANDO" | "PENSANDO" | "MAO_NA_CABECA" | "DINHEIRO" | "POSITIVO" | "NEGATIVO"
  | "FACEPALM" | "ASSUSTADO" | "DINHEIRO_DOENDO" | "SUSSURRO" | "NEGANDO" | "CONCORDANDO";

/** The host participates in the scene instead of sitting fixed in a corner:
 *  it can enter from a side, sit centered/enlarged for a reaction beat, or
 *  stay in its default reading spot — BUYER_PAIN_V2 adds foreground
 *  left/right so it can read as "in the scene", not just a corner watermark. */
export type MascotPosition = "BOTTOM_RIGHT" | "BOTTOM_LEFT" | "TOP_RIGHT" | "TOP_LEFT" | "CENTER" | "FOREGROUND_LEFT" | "FOREGROUND_RIGHT";
export type MascotEnterFrom = "LEFT" | "RIGHT" | "NONE";

export interface TimedSfx {
  type: "WHOOSH" | "POP" | "CLICK" | "IMPACT" | "RISER";
  src: string; // staticFile-relative path
  offsetSec?: number; // within the block
}

export interface VideoCut {
  src: string; // staticFile-relative path
  startFromSec?: number;
  camera?: "PUSH_IN" | "PUSH_OUT" | "STATIC";
}

export interface TimedBlock {
  id: string;
  startSec: number;
  durationSec: number;
  /** 1 entry = one shot for the whole block; 2+ = an internal hard cut so no
   *  block ever holds a single static composition for more than ~2s. */
  videoCuts: VideoCut[];
  keyword?: string;
  keywordVariant?: "NORMAL" | "BIG_NUMBER";
  keywordOffsetSec?: number;
  /** HOST_SAFE_ZONE / KINETIC_TEXT_SAFE_ZONE collision avoidance
   *  (buyer-pain-v2): computed once in code from the host's real
   *  position+size for this beat, never left to overlap by chance. */
  keywordTextPosition?: "TOP" | "CENTER" | "BOTTOM";
  mascotPose?: MascotPose;
  mascotPunchIn?: boolean;
  mascotPosition?: MascotPosition;
  mascotEnterFrom?: MascotEnterFrom;
  mascotScale?: number;
  patternInterrupt?: boolean;
  sfx?: TimedSfx;
  // P0 additions (2026-09-15): optional per-beat overrides.
  visualRegister?: VisualRegister;
  screenEvidence?: ScreenEvidenceProps;
  hookBlock?: HookBlock;
}

export interface NarratedReelV3Props {
  blocks: TimedBlock[];
  /** MAISCAR_VOICE_LOCK (format-lock v1): ONE narration file for the whole
   *  Reel, generated by a SINGLE TTS call — never per-block files, so there
   *  is structurally no possibility of a voice/config change mid-video. */
  narrationSrc: string;
  musicSrc?: string;
  fps: number;
}

// -----------------------------------------------------------------------------
// P0 additions (2026-09-15) — additive-only, all optional. Nothing existing
// changes shape; every downstream consumer can ignore these until wired.
// -----------------------------------------------------------------------------

/**
 * Visual register a beat occupies on screen. Used by:
 *  - the Haiku writer to distribute registers across a Reel
 *  - the QA gate REGISTER_COUNT >= 4
 *  - the POWERPOINT_STYLE detector
 *  - the renderer to route SCREEN_EVIDENCE beats to <ScreenEvidence />
 */
export type VisualRegister =
  | "PRESENTER_FACE"     // mascot reaction shot in a corner
  | "SCREEN_EVIDENCE"    // phone-frame with a plausible page inside it
  | "PRODUCT_MACRO"      // close-up of a car part, tire, dashboard, key
  | "DOCUMENT"           // contract, receipt, sticker, VIN plate
  | "LOCATION_BROLL"     // mechanic bay, dealership floor, road, gas station
  | "BIG_NUMBER"         // full-frame kinetic number (R$, %, months, years)
  | "MONEY_STACK";       // cash, cards, calculator, PIX screen

/**
 * The HOOK is a separate produced asset from the rest of the Reel. When set on
 * beat 0, the renderer forces mascot off for the first 15 frames, slams the
 * `firstOnScreenText` onto frame 1, and QA enforces HOOK_FIRST_WORD_LATENCY
 * <= 200ms plus FIRST_ON_SCREEN_TEXT presence.
 */
export interface HookBlock {
  firstOnScreenText: string;              // 3-5 words, ALL CAPS by convention
  firstShotRegister: "PRESENTER_FACE" | "SCREEN_EVIDENCE" | "PRODUCT_MACRO";
  /** Optional; the pipeline measures this from the assembled narration MP3. */
  voiceStartOffsetMs?: number;
}

/**
 * Deterministic props for a SCREEN_EVIDENCE beat. The pipeline composes these
 * from the beat's own claim + tier — never a real screenshot of a real
 * service. Rendering happens in <ScreenEvidence /> (packages/backend/remotion/ScreenEvidence.tsx).
 */
export type ScreenEvidenceTemplate =
  | "FINANCING_QUOTE"    // parcela x N | CET | R$ total
  | "LISTING_PAGE"       // marketplace card
  | "WHATSAPP_THREAD"    // seller vs. buyer chat
  | "PIX_RECEIPT"        // transfer confirmation
  | "INVOICE";           // service invoice

export interface ScreenEvidenceProps {
  template: ScreenEvidenceTemplate;
  /** Free-form key/value pairs interpolated into the template. */
  values: Record<string, string>;
  /** Optional highlight: which key(s) should pulse/underline on-screen. */
  highlight?: string[];
}

/**
 * Adds VisualRegister / HookBlock / ScreenEvidenceProps to TimedBlock as
 * OPTIONAL fields. Old callers that don't set them continue to work; new
 * callers can use them without a breaking migration.
 */
export interface TimedBlockV3Additions {
  visualRegister?: VisualRegister;
  hookBlock?: HookBlock;
  screenEvidence?: ScreenEvidenceProps;
}
