import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

/**
 * MAIS.CAR — MASTER DIAGONAL (Visual Lock, 2026-09-03). Uma única
 * assinatura visual de produção — não uma coleção de templates. Toda peça
 * de feed tem: moldura (cantos em L) + logo fixo + fotografia dominante
 * (≥65% da área, alvo 68–75%) + corte diagonal + título/complemento em
 * escala fixa e contida. EDITORIAL/DATA/SPLIT (sem foto e/ou sem diagonal)
 * ficam desativados no dispatcher — ver renderSlideV4. Espelhamento
 * (`flip`) é a única variação controlada permitida (rule 17).
 *
 * Ver platform/docs/MAISCAR_EDITORIAL_DESIGN_SYSTEM.md (fonte de verdade)
 * e platform/content-review/MAISCAR_GOLDEN_MASTER.png (referência visual).
 *
 * Regras duras, sem exceção:
 * - Tamanhos de título/complemento são CONGELADOS (TITLE_SIZE/BODY_SIZE) —
 *   nunca crescem nem encolhem para acomodar texto. Se não couber, lança
 *   HeadlineOverflowError: reescreva a copy, não o design system.
 * - PHOTO_DOMINANT é um invariante geométrico (assertPhotoDominant) — texto
 *   nunca pode crescer a ponto de a foto cair abaixo de 65% da arte.
 * - Nunca trunca com "…".
 */

export const MAISCAR_RED = "#A00223";
export const INK = "#181614";
// Off-white editorial, não branco puro: testado lado a lado (ver
// content-review/design-system-diagonal-v4/bg-compare/) — o branco puro lia
// como "apresentação corporativa" ao lado de fotografia automotiva com muito
// contraste; este tom de papel aproxima de revista impressa premium sem
// virar bege. Decisão do art direction desta rodada, não solicita mais teste.
export const PANEL_BG = "#F6F4EF";
const LOGO_PATH = path.join(__dirname, "..", "..", "..", "assets", "maiscar-logo-mark.png");

export const W = 1080;
export const H = 1350;

const MARGIN_X = 76;
export const FRAME_INSET = 30;

const HEADLINE_TARGET = 96;
const HEADLINE_MIN = 80;
const HEADLINE_LEAD_RATIO = 0.94;
const COMPLEMENT_TARGET = 58;
const COMPLEMENT_MIN = 48;
export const BEBAS_GLYPH_FACTOR = 0.42; // condensed caps — narrower per character than a normal sans
export const BAHN_GLYPH_FACTOR = 0.52;

export class HeadlineOverflowError extends Error {
  constructor(line: string, available: number) {
    super(
      `Linha "${line}" não cabe na safe zone mesmo no tamanho mínimo (largura disponível ~${Math.round(available)}px). ` +
        `Reescreva a frase mais curta — o renderer não trunca nem encolhe além do piso.`,
    );
    this.name = "HeadlineOverflowError";
  }
}

/**
 * Clean Export Rule — bloqueia a exportação (não corrige silenciosamente)
 * se qualquer texto que vai pra dentro da arte contiver metadado de
 * produção (fonte de imagem, IA, watermark, path, URL) ou continuidade
 * falsa ("deslize"/"arraste"/"continue"). Fonte editorial de fato
 * ("Fonte: dados oficiais...") pertence à legenda, nunca à peça — por
 * isso a lista bane "fonte" também, sem exceção dentro da arte.
 */
export class CleanExportError extends Error {
  constructor(field: string, matched: string) {
    super(`Clean Export Rule bloqueou a exportação: campo "${field}" contém "${matched}" — isso é metadado de produção ou continuidade falsa, não pode ir para a arte. Corrija o texto (fonte vai na legenda, não na peça).`);
    this.name = "CleanExportError";
  }
}

const BANNED_TERMS = [
  "deslize", "arraste", "continue", "próximo slide", "proximo slide", "swipe",
  "pexels", "unsplash", "shutterstock", "getty", "istock", "gerado por", "ai generated",
  "generated by", "midjourney", "pollinations", "dall-e", "dalle", "stable diffusion",
  "prompt:", "foto:", "imagem:", "fonte:", "fonte da imagem", "source:", "credit:",
  "crédito:", "watermark", "placeholder",
];
const URL_OR_PATH_RE = /(https?:\/\/|www\.|[a-zA-Z]:\\|\/Users\/|\/home\/|\.(png|jpe?g|webp|gif)\b)/i;

function assertCleanExport(fields: Record<string, string | undefined>) {
  for (const [field, value] of Object.entries(fields)) {
    if (!value) continue;
    const lower = value.toLowerCase();
    for (const term of BANNED_TERMS) {
      if (lower.includes(term)) throw new CleanExportError(field, term);
    }
    const urlMatch = value.match(URL_OR_PATH_RE);
    if (urlMatch) throw new CleanExportError(field, urlMatch[0]);
  }
}

function esc(t: string) {
  return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function fitsAtSize(line: string, fontSize: number, maxWidthPx: number, glyphFactor = BEBAS_GLYPH_FACTOR): boolean {
  return line.length * fontSize * glyphFactor <= maxWidthPx;
}

// Greedy word-wrap for free-form support text (captions, body, data labels)
// that isn't pre-broken into lines by the caller — the DATA family's
// `caption` field originally skipped this entirely and rendered as one
// unbroken line, which overflowed past the frame on anything longer than a
// few words (caught visually during QA on the ADAS post, 2026-09-03).
function wrapText(text: string, fontSize: number, maxWidthPx: number, glyphFactor = BAHN_GLYPH_FACTOR, maxLines = 2): string[] {
  const maxChars = Math.max(6, Math.floor(maxWidthPx / (fontSize * glyphFactor)));
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length > maxChars && current) {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current) lines.push(current);
  if (lines.length > maxLines) {
    throw new HeadlineOverflowError(text, maxWidthPx);
  }
  return lines;
}

/** Resolves one text tier to a font size within [min,target] — no floor-less shrinking, no ellipsis. Throws if even `min` doesn't fit. */
function resolveTierSize(lines: string[], target: number, min: number, maxWidthPx: number, glyphFactor = BEBAS_GLYPH_FACTOR): number {
  for (const line of lines) {
    if (!fitsAtSize(line, min, maxWidthPx, glyphFactor)) {
      throw new HeadlineOverflowError(line, maxWidthPx);
    }
  }
  let size = target;
  while (size > min && lines.some((l) => !fitsAtSize(l, size, maxWidthPx, glyphFactor))) {
    size -= 2;
  }
  return Math.max(size, min);
}

async function gradedPhoto(photoPath: string | Buffer, position?: string, saturation?: number): Promise<Buffer> {
  return sharp(photoPath)
    .resize(W, H, { fit: "cover", position: position ?? "centre" })
    .modulate({ saturation: saturation ?? 0.88, brightness: 1.0 })
    .linear(1.08, -12) // fixed brand grade — same on every photo regardless of source
    .png()
    .toBuffer();
}

async function officialLogo(targetW = 168): Promise<{ buf: Buffer; w: number; h: number }> {
  const buf = await sharp(LOGO_PATH).resize({ width: targetW }).png().toBuffer();
  const meta = await sharp(buf).metadata();
  return { buf, w: targetW, h: meta.height ?? Math.round(targetW * 0.4) };
}

function cornerBrackets(): string {
  const len = 54;
  const o1 = FRAME_INSET;
  const o2 = FRAME_INSET + 8;
  const corners: Array<[number, number, number, number]> = [
    [o1, o1, 1, 1],
    [W - o1, o1, -1, 1],
    [o1, H - o1, 1, -1],
    [W - o1, H - o1, -1, -1],
  ];
  return corners
    .map(
      ([x, y, dx, dy]) => `
      <path d="M ${x} ${y + dy * len} L ${x} ${y} L ${x + dx * len} ${y}" fill="none" stroke="${MAISCAR_RED}" stroke-width="3" />
      <path d="M ${x + dx * (o2 - o1)} ${y + dy * (len - 14)} L ${x + dx * (o2 - o1)} ${y + dy * (o2 - o1)} L ${x + dx * (len - 14)} ${y + dy * (o2 - o1)}" fill="none" stroke="${MAISCAR_RED}" stroke-width="1" stroke-opacity="0.55" />
    `,
    )
    .join("\n");
}

/** Samples a region of a rendered base (photo or flat panel) and returns a legible ink/halo pair — used by folio and any text sitting on a variable background. */
async function adaptiveInk(base: Buffer, zone: { left: number; top: number; width: number; height: number }) {
  const clampedZone = {
    left: Math.max(0, Math.min(zone.left, W - 1)),
    top: Math.max(0, Math.min(zone.top, H - 1)),
    width: Math.max(1, Math.min(zone.width, W - Math.max(0, zone.left))),
    height: Math.max(1, Math.min(zone.height, H - Math.max(0, zone.top))),
  };
  const region = await sharp(base).extract(clampedZone).grayscale().stats();
  const onDark = region.channels[0].mean < 130;
  return { color: onDark ? "#FFFFFF" : "#2A2A2A", halo: onDark ? "#000000" : "#FFFFFF", onDark };
}

function folioSvg(pageLabel: string | undefined, ink: { color: string; halo: string }): string {
  if (!pageLabel) return "";
  return `<text x="${W - MARGIN_X}" y="${H - 52}" font-family="Bahnschrift SemiBold" font-weight="600" font-size="24" letter-spacing="2" fill="${ink.halo}" fill-opacity="0.85" text-anchor="end" filter="url(#wmHalo)">${esc(pageLabel)}</text>
     <text x="${W - MARGIN_X}" y="${H - 52}" font-family="Bahnschrift SemiBold" font-weight="600" font-size="24" letter-spacing="2" fill="${ink.color}" text-anchor="end">${esc(pageLabel)}</text>`;
}

function defsBlock(): string {
  return `<filter id="wmHalo" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="5"/></filter>`;
}

// ---------------------------------------------------------------------------
// HERO — full-bleed photo, diagonal text panel on top. The system's cover /
// closer treatment: photo is the loudest thing on the slide.
// ---------------------------------------------------------------------------

export interface HeroInput {
  family?: "hero";
  photoPath: string | Buffer;
  kicker: string;
  headline: string[];
  complement?: string;
  microCaption?: string;
  pageLabel?: string;
  flip?: boolean;
  photoPosition?: string;
  gradeSaturation?: number;
  /**
   * SEMANTIC_IMAGE_MATCH — required, no default. This can't be verified by
   * code (no vision model in this pipeline), so it's a deliberate attestation
   * instead of a silent assumption: the caller confirms, at the moment this
   * specific photo was chosen for this specific content, that it actually
   * depicts/relates to what the headline says — not just "a nice car photo".
   * Passing `true` without having made that check defeats the point of the
   * gate; the field exists so skipping the check requires typing `true`
   * explicitly, not benefiting from an implicit default.
   */
  semanticMatchReviewed: boolean;
  /**
   * SEMANTIC_PHOTO_MATCH — which kind of photo this is, declared explicitly
   * so the code (not just the caller's memory) can catch the exact mistake
   * this gate exists for: text that names a specific model paired with a
   * photo of a different one.
   * - EXACT_VEHICLE: the photo shows the specific model the copy is about.
   * - CONTEXTUAL: a real photo relevant to the topic but not that specific
   *   model — only valid when `namedVehicle` is NOT set (the copy must stay
   *   generic; it can't name a model this photo doesn't show).
   * - DOCUMENTARY: real contextual photo of a process/place (oficina,
   *   trânsito, concessionária, documento) rather than a vehicle at all.
   */
  photoCategory: "EXACT_VEHICLE" | "CONTEXTUAL" | "DOCUMENTARY";
  /** Set this to the specific model name when the kicker/headline names one — forces photoCategory to EXACT_VEHICLE. Leave unset for generic copy. */
  namedVehicle?: string;
}

export class SemanticPhotoMismatchError extends Error {
  constructor(namedVehicle: string, category: string) {
    super(
      `SEMANTIC_PHOTO_MATCH bloqueou a exportação: a copy nomeia "${namedVehicle}" mas a foto está marcada como "${category}", não EXACT_VEHICLE. ` +
        `Não troque a pauta silenciosamente pra caber a foto disponível — ou ache uma foto real desse modelo, ou reescreva a copy pra ficar genérica (e então marque a foto como CONTEXTUAL), ou descarte esta pauta.`,
    );
    this.name = "SemanticPhotoMismatchError";
  }
}

// ---------------------------------------------------------------------------
// MASTER DIAGONAL — brand constants, frozen 2026-09-03 after the Visual Lock
// directive. This is now the ONLY production template (see the dispatcher at
// the bottom of the file, which refuses every other family for the feed).
// These sizes do NOT auto-scale: a title/complement that doesn't fit at the
// frozen size throws HeadlineOverflowError instead of shrinking — rewrite
// the copy, never the design system.
// ---------------------------------------------------------------------------
export const TITLE_SIZE = 76; // token "15" — ratio to BODY preserved at ~15:13
export const BODY_SIZE = 66; // token "13"
const DIAGONAL_DIFF = 76;
// Panel height is capped tight enough that the text zone can never exceed
// ~30% of canvas height (photo target 70–75%) — see PHOTO_RATIO_MIN below.
// The panel does not "grow to fit more copy"; short copy is a hard
// requirement enforced by geometry, not a style preference.
const PANEL_RIGHT_DEFAULT = 320;
const PANEL_RIGHT_MAX = 394;
export const PHOTO_RATIO_MIN = 0.68; // hard block below this — tightened 2026-09-03 (was 0.65)
export const PHOTO_RATIO_TARGET = [0.7, 0.75] as const;

export class VisualIdentityError extends Error {
  constructor(reason: string) {
    super(`Visual Identity Gate bloqueou a publicação: ${reason}`);
    this.name = "VisualIdentityError";
  }
}

/**
 * PHOTO_DOMINANT invariant — computed from the trapezoid panel's average
 * height. Throws, never adjusts. Exported (not just used inline by
 * renderHero) so chaos tests can exercise this invariant directly with
 * fabricated panel geometry — renderHero's own public params can't be
 * driven to an out-of-range photoRatio through legitimate copy alone, since
 * HeadlineOverflowError fires first once text gets that long.
 */
export function assertPhotoDominant(panelLeftY: number, panelRightY: number): number {
  const avgPanelHeight = (panelLeftY + panelRightY) / 2;
  const photoRatio = 1 - avgPanelHeight / H;
  if (photoRatio < PHOTO_RATIO_MIN) {
    throw new VisualIdentityError(
      `photoRatio ${photoRatio.toFixed(2)} abaixo do piso ${PHOTO_RATIO_MIN} — texto grande demais para a identidade Mais.Car. Encurte o título/complemento.`,
    );
  }
  return photoRatio;
}

/**
 * TITLE_SIZE/BODY_SIZE are exported consts, so nothing outside this module
 * can silently redefine them — but a future edit *inside* this file could
 * still pass a different literal into the SVG by mistake. This assertion is
 * the tripwire: it re-checks the actual values used at render time against
 * the frozen tokens, so that mistake fails loudly instead of drifting.
 */
function assertFrozenTypeScale(usedTitleSize: number, usedBodySize?: number) {
  if (usedTitleSize !== TITLE_SIZE) {
    throw new VisualIdentityError(`TITLE_SCALE alterado em runtime (${usedTitleSize} != ${TITLE_SIZE}) — tamanho é token congelado.`);
  }
  if (usedBodySize !== undefined && usedBodySize !== BODY_SIZE) {
    throw new VisualIdentityError(`BODY_SCALE alterado em runtime (${usedBodySize} != ${BODY_SIZE}) — tamanho é token congelado.`);
  }
}

/**
 * HAS_LOGO / HAS_FRAME / HAS_DIAGONAL, checked on the actual rendered pixels
 * — not just "the SVG string that draws them exists". Catches real failures
 * (logo asset missing/blank, composite order broken) that a purely
 * structural check would miss. Samples small windows at the fixed
 * coordinates every render uses.
 */
/**
 * Exported for the same reason as assertPhotoDominant above: HAS_LOGO/
 * HAS_FRAME/HAS_DIAGONAL can't be forced to fail through renderHero's real
 * inputs (the logo asset and frame/seam drawing are internal, not caller-
 * controlled), so chaos tests call this directly against synthetic PNGs
 * that deliberately omit one element at a time.
 */
export async function assertStructuralElements(finalPng: Buffer, logo: { x: number; y: number; w: number; h: number }, seam: { x: number; y: number }) {
  const img = sharp(finalPng);

  // Materialize the extracted region to a buffer before calling .stats() on
  // a fresh sharp instance — chaining .extract().stats() directly on the
  // same pipeline was observed to return a nonzero stdev (up to ~2.6) even
  // for a provably flat region (verified against a raw-decoded pixel dump),
  // which silently let a blank logo region pass the HAS_LOGO check.
  const logoBuf = await img.clone().extract({ left: logo.x, top: logo.y, width: logo.w, height: Math.max(1, logo.h) }).png().toBuffer();
  const logoRegion = await sharp(logoBuf).stats();
  const logoVariance = logoRegion.channels.reduce((sum, c) => sum + c.stdev, 0);
  if (logoVariance < 2) {
    throw new VisualIdentityError("HAS_LOGO falhou — região do logo está uniforme/em branco no PNG final (asset não compositado).");
  }

  const frameSample = await img.clone().extract({ left: FRAME_INSET - 2, top: FRAME_INSET - 2, width: 60, height: 4 }).removeAlpha().raw().toBuffer();
  const hasFrameColor = pixelBufferContainsRed(frameSample);
  if (!hasFrameColor) {
    throw new VisualIdentityError("HAS_FRAME falhou — canto em L não encontrado no pixel esperado.");
  }

  const seamSample = await img.clone().extract({ left: Math.max(0, seam.x - 30), top: seam.y - 2, width: 60, height: 4 }).removeAlpha().raw().toBuffer();
  if (!pixelBufferContainsRed(seamSample)) {
    throw new VisualIdentityError("HAS_DIAGONAL falhou — costura da diagonal não encontrada no pixel esperado.");
  }
}

function pixelBufferContainsRed(raw: Buffer): boolean {
  // MAISCAR_RED #A00223 → r≈160,g≈2,b≈35. Scan for any pixel close to it
  // (small tolerance for the halo/antialiasing blend against the photo).
  for (let i = 0; i + 2 < raw.length; i += 3) {
    const r = raw[i], g = raw[i + 1], b = raw[i + 2];
    if (r > 120 && r < 210 && g < 60 && b > 10 && b < 90) return true;
  }
  return false;
}

export async function renderHero(input: HeroInput): Promise<Buffer> {
  assertCleanExport({
    kicker: input.kicker,
    ...Object.fromEntries(input.headline.map((l, i) => [`headline[${i}]`, l])),
    complement: input.complement,
    microCaption: input.microCaption,
    pageLabel: input.pageLabel,
  });
  if (!input.photoPath) throw new VisualIdentityError("HAS_PHOTO falhou — toda publicação Mais.Car exige fotografia semanticamente relacionada.");
  if (input.semanticMatchReviewed !== true) {
    throw new VisualIdentityError(
      "SEMANTIC_IMAGE_MATCH não confirmado — passe semanticMatchReviewed:true só depois de checar que a foto escolhida realmente corresponde ao conteúdo (não é gerada por código, é atestação de quem chama).",
    );
  }
  if (input.namedVehicle && input.photoCategory !== "EXACT_VEHICLE") {
    throw new SemanticPhotoMismatchError(input.namedVehicle, input.photoCategory);
  }
  assertFrozenTypeScale(TITLE_SIZE, BODY_SIZE);

  const flip = input.flip ?? false;
  const graded = await gradedPhoto(input.photoPath, input.photoPosition, input.gradeSaturation);

  const safeTop = FRAME_INSET + 36;
  const safeWidth = W - MARGIN_X - 100;
  const textX = flip ? W - MARGIN_X : MARGIN_X;
  const textAnchor = flip ? "end" : "start";

  // Fixed sizes — no shrink window. A line that doesn't fit means the copy
  // is too long, not that the type scale is negotiable (rule 10/11).
  for (const line of input.headline) {
    if (!fitsAtSize(line, TITLE_SIZE, safeWidth)) throw new HeadlineOverflowError(line, safeWidth);
  }
  if (input.complement && !fitsAtSize(input.complement, BODY_SIZE, safeWidth)) {
    throw new HeadlineOverflowError(input.complement, safeWidth);
  }
  if (input.microCaption && !fitsAtSize(input.microCaption, Math.round(BODY_SIZE * 0.85), safeWidth, BAHN_GLYPH_FACTOR)) {
    throw new HeadlineOverflowError(input.microCaption, safeWidth);
  }
  const headlineSize = TITLE_SIZE;
  const headlineLead = Math.round(headlineSize * HEADLINE_LEAD_RATIO);

  const kickerCapHeight = 21 * 0.73;
  const kickerY = safeTop + kickerCapHeight;
  const headlineCapHeight = headlineSize * 0.73;
  const headlineStartY = kickerY + 14 + 22 + headlineCapHeight;
  const headlineEndY = headlineStartY + (input.headline.length - 1) * headlineLead;

  let complementSize = 0;
  let complementY = 0;
  if (input.complement) {
    complementSize = BODY_SIZE;
    complementY = headlineEndY + 22 + complementSize * 0.73;
  }

  let microCaptionY = 0;
  if (input.microCaption) {
    const afterY = input.complement ? complementY : headlineEndY;
    // Same BODY_SIZE tier as complement, just a touch lighter — never the
    // old "3-4x smaller" caption that violated the contained-hierarchy rule.
    microCaptionY = afterY + 20 + BODY_SIZE * 0.85 * 0.73;
  }

  const contentBottom = input.microCaption ? microCaptionY : input.complement ? complementY : headlineEndY;
  const panelRightY = Math.min(PANEL_RIGHT_MAX, Math.max(PANEL_RIGHT_DEFAULT, contentBottom + 30));
  const panelLeftY = panelRightY + DIAGONAL_DIFF;
  const safeBottom = panelRightY - 26;
  if (contentBottom > safeBottom) {
    throw new HeadlineOverflowError(input.microCaption ?? input.complement ?? input.headline[input.headline.length - 1], safeWidth);
  }
  assertPhotoDominant(panelLeftY, panelRightY);

  const pageInk = await adaptiveInk(graded, { left: W - 220, top: H - 110, width: 220, height: 110 });

  const headlineSvg = input.headline
    .map(
      (line, i) =>
        `<text x="${textX}" y="${headlineStartY + i * headlineLead}" font-family="Bebas Neue" font-size="${headlineSize}" fill="${MAISCAR_RED}" letter-spacing="0.5" text-anchor="${textAnchor}">${esc(line.toUpperCase())}</text>`,
    )
    .join("\n");

  const { buf: logoBuf, w: logoW, h: logoH } = await officialLogo();
  const logoX = flip ? MARGIN_X : W - MARGIN_X - logoW;
  const logoY = FRAME_INSET + 28;

  const panelPoly = flip
    ? `0,${panelRightY} ${W},${panelLeftY} ${W},0 0,0`
    : `0,0 ${W},0 ${W},${panelRightY} 0,${panelLeftY}`;
  const seamY1 = flip ? panelRightY : panelLeftY;
  const seamY2 = flip ? panelLeftY : panelRightY;

  const svg = `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
    <defs>${defsBlock()}<clipPath id="panelClip"><polygon points="${panelPoly}" /></clipPath></defs>

    <polygon points="${panelPoly}" fill="${PANEL_BG}" />
    <line x1="0" y1="${seamY1}" x2="${W}" y2="${seamY2}" stroke="${MAISCAR_RED}" stroke-width="4" />
    <line x1="0" y1="${seamY1 + 12}" x2="${W}" y2="${seamY2 + 12}" stroke="${MAISCAR_RED}" stroke-width="1.5" stroke-opacity="0.5" />
    ${Array.from({ length: 14 })
      .map((_, i) => {
        const t = i / 13;
        const x = t * W;
        const y = seamY1 + (seamY2 - seamY1) * t;
        return `<line x1="${x}" y1="${y - 9}" x2="${x}" y2="${y - 2}" stroke="${MAISCAR_RED}" stroke-width="1.5" stroke-opacity="0.65" />`;
      })
      .join("\n")}

    <g clip-path="url(#panelClip)">
      <text x="${textX}" y="${kickerY}" font-family="Bahnschrift SemiBold" font-weight="600" font-size="21" letter-spacing="5" fill="${INK}" text-anchor="${textAnchor}">${esc(input.kicker.toUpperCase())}</text>
      ${flip ? `<line x1="${W - MARGIN_X - 70}" y1="${kickerY + 14}" x2="${W - MARGIN_X}" y2="${kickerY + 14}" stroke="${MAISCAR_RED}" stroke-width="3" />` : `<line x1="${MARGIN_X}" y1="${kickerY + 14}" x2="${MARGIN_X + 70}" y2="${kickerY + 14}" stroke="${MAISCAR_RED}" stroke-width="3" />`}
      ${headlineSvg}
      ${input.complement ? `<text x="${textX}" y="${complementY}" font-family="Bebas Neue" font-size="${complementSize}" fill="${INK}" letter-spacing="0.5" text-anchor="${textAnchor}">${esc(input.complement.toUpperCase())}</text>` : ""}
      ${input.microCaption ? `<text x="${textX}" y="${microCaptionY}" font-family="Bahnschrift SemiBold" font-weight="500" font-size="${Math.round(BODY_SIZE * 0.85)}" fill="${INK}" fill-opacity="0.75" text-anchor="${textAnchor}">${esc(input.microCaption)}</text>` : ""}
    </g>

    ${cornerBrackets()}
    <image href="data:image/png;base64,${logoBuf.toString("base64")}" x="${logoX}" y="${logoY}" width="${logoW}" height="${logoH}" />
    ${folioSvg(input.pageLabel, pageInk)}
  </svg>`;

  const finalPng = await sharp(graded).composite([{ input: Buffer.from(svg), top: 0, left: 0 }]).png().toBuffer();
  await assertStructuralElements(
    finalPng,
    { x: logoX, y: logoY, w: logoW, h: logoH },
    { x: Math.round(W / 2), y: Math.round((seamY1 + seamY2) / 2) },
  );
  return finalPng;
}

// ---------------------------------------------------------------------------
// EDITORIAL — text dominant, photo as a framed inset (not full-bleed). Used
// for slides that carry a fact/finding rather than a cover moment.
// ---------------------------------------------------------------------------

export interface EditorialInput {
  family: "editorial";
  photoPath: string | Buffer;
  kicker: string;
  headline: string[];
  body?: string; // one supporting sentence, ink, below the headline — this family allows a bit more than HERO's microCaption
  pageLabel?: string;
  flip?: boolean;
  photoPosition?: string;
  gradeSaturation?: number;
}

export async function renderEditorial(input: EditorialInput): Promise<Buffer> {
  assertCleanExport({
    kicker: input.kicker,
    ...Object.fromEntries(input.headline.map((l, i) => [`headline[${i}]`, l])),
    body: input.body,
    pageLabel: input.pageLabel,
  });
  const flip = input.flip ?? false;
  const textX = flip ? W - MARGIN_X : MARGIN_X;
  const textAnchor = flip ? "end" : "start";
  const safeWidth = W - MARGIN_X - 100;

  const insetX = MARGIN_X - 6;
  const insetW = W - (MARGIN_X - 6) * 2;

  const headlineSize = resolveTierSize(input.headline, HEADLINE_TARGET, HEADLINE_MIN, safeWidth);
  const headlineLead = Math.round(headlineSize * HEADLINE_LEAD_RATIO);

  const safeTop = FRAME_INSET + 40;
  const kickerY = safeTop + 21 * 0.73;
  const headlineStartY = kickerY + 14 + 26 + headlineSize * 0.73;
  const headlineEndY = headlineStartY + (input.headline.length - 1) * headlineLead;

  let bodySize = 0;
  const bodyLines: string[] = [];
  let bodyEndY = headlineEndY;
  if (input.body) {
    bodySize = 30;
    const maxChars = Math.max(10, Math.floor(safeWidth / (bodySize * BAHN_GLYPH_FACTOR)));
    const words = input.body.split(/\s+/);
    let current = "";
    for (const w of words) {
      const cand = current ? `${current} ${w}` : w;
      if (cand.length > maxChars && current) {
        bodyLines.push(current);
        current = w;
      } else current = cand;
    }
    if (current) bodyLines.push(current);
    if (bodyLines.length > 3) throw new HeadlineOverflowError(input.body, safeWidth);
    const bodyLead = 40;
    bodyLines.forEach((_, i) => {
      bodyEndY = headlineEndY + 30 + i * bodyLead + bodySize * 0.73;
    });
  }

  // Photo inset is derived from the text block, not fixed — it starts right
  // after the copy ends and fills the rest of the canvas down to the frame.
  // Text-dominant slides (short body) get a bigger photo; longer copy gets a
  // smaller one — this is what keeps "negative space" intentional instead of
  // leftover dead space between two independently-positioned blocks.
  const insetY = Math.round(bodyEndY + 50);
  const insetBottomLimit = H - FRAME_INSET - 46;
  const insetH = Math.round(Math.max(320, insetBottomLimit - insetY));
  if (insetY + 320 > insetBottomLimit) {
    throw new HeadlineOverflowError(input.body ?? input.headline[input.headline.length - 1], safeWidth);
  }

  const photoBuf = await sharp(await gradedPhoto(input.photoPath, input.photoPosition, input.gradeSaturation))
    .extract({ left: 0, top: 0, width: W, height: H })
    .resize(insetW, insetH, { fit: "cover" })
    .png()
    .toBuffer();

  const pageInk = await adaptiveInk(photoBuf, { left: insetW - 220, top: insetH - 100, width: 220, height: 100 });

  const { buf: logoBuf, w: logoW, h: logoH } = await officialLogo();
  const logoX = flip ? MARGIN_X : W - MARGIN_X - logoW;
  const logoY = FRAME_INSET + 28;

  const bodySvg = bodyLines
    .map((l, i) => `<text x="${textX}" y="${headlineEndY + 30 + i * 40}" font-family="Bahnschrift SemiBold" font-weight="500" font-size="${bodySize}" fill="${INK}" fill-opacity="0.75" text-anchor="${textAnchor}">${esc(l)}</text>`)
    .join("\n");

  const svg = `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
    <defs>${defsBlock()}</defs>
    <rect width="${W}" height="${H}" fill="${PANEL_BG}" />

    <text x="${textX}" y="${kickerY}" font-family="Bahnschrift SemiBold" font-weight="600" font-size="21" letter-spacing="5" fill="${INK}" text-anchor="${textAnchor}">${esc(input.kicker.toUpperCase())}</text>
    ${flip ? `<line x1="${W - MARGIN_X - 70}" y1="${kickerY + 14}" x2="${W - MARGIN_X}" y2="${kickerY + 14}" stroke="${MAISCAR_RED}" stroke-width="3" />` : `<line x1="${MARGIN_X}" y1="${kickerY + 14}" x2="${MARGIN_X + 70}" y2="${kickerY + 14}" stroke="${MAISCAR_RED}" stroke-width="3" />`}
    ${input.headline.map((line, i) => `<text x="${textX}" y="${headlineStartY + i * headlineLead}" font-family="Bebas Neue" font-size="${headlineSize}" fill="${MAISCAR_RED}" letter-spacing="0.5" text-anchor="${textAnchor}">${esc(line.toUpperCase())}</text>`).join("\n")}
    ${bodySvg}

    <!-- foto: moldura retangular fina, cantos em L reduzidos — mesma linguagem do frame externo, escala menor -->
    <image href="data:image/png;base64,${photoBuf.toString("base64")}" x="${insetX}" y="${insetY}" width="${insetW}" height="${insetH}" />
    <rect x="${insetX}" y="${insetY}" width="${insetW}" height="${insetH}" fill="none" stroke="${MAISCAR_RED}" stroke-width="2.5" />
    <path d="M ${insetX} ${insetY + 30} L ${insetX} ${insetY} L ${insetX + 30} ${insetY}" fill="none" stroke="${MAISCAR_RED}" stroke-width="3" />
    <path d="M ${insetX + insetW - 30} ${insetY + insetH} L ${insetX + insetW} ${insetY + insetH} L ${insetX + insetW} ${insetY + insetH - 30}" fill="none" stroke="${MAISCAR_RED}" stroke-width="3" />

    ${cornerBrackets()}
    <image href="data:image/png;base64,${logoBuf.toString("base64")}" x="${logoX}" y="${logoY}" width="${logoW}" height="${logoH}" />
    ${folioSvg(input.pageLabel, pageInk)}
  </svg>`;

  const base = await sharp({ create: { width: W, height: H, channels: 4, background: PANEL_BG } }).png().toBuffer();
  return sharp(base).composite([{ input: Buffer.from(svg), top: 0, left: 0 }]).png().toBuffer();
}

// ---------------------------------------------------------------------------
// DATA — no photo. Typography + a number or a pull-quote + negative space.
// Used when the point is a fact/figure, or when no legitimate photo of the
// specific thing exists (never fake one in — see design-system doc).
// ---------------------------------------------------------------------------

export interface DataInput {
  family: "data";
  mode: "quote" | "stat";
  kicker: string;
  /** mode "quote": the quoted line(s). mode "stat": the big number/price, e.g. "R$ 150–180 MIL". */
  headline: string[];
  /** mode "quote": attribution, e.g. "— compradores, em carta ao CEO". mode "stat": one short explainer line. */
  caption?: string;
  pageLabel?: string;
}

export async function renderData(input: DataInput): Promise<Buffer> {
  assertCleanExport({
    kicker: input.kicker,
    ...Object.fromEntries(input.headline.map((l, i) => [`headline[${i}]`, l])),
    caption: input.caption,
    pageLabel: input.pageLabel,
  });
  const textX = MARGIN_X;
  const safeWidth = W - MARGIN_X * 2;
  const isQuote = input.mode === "quote";

  const headlineTarget = isQuote ? 84 : 132;
  const headlineMin = isQuote ? 68 : 96;
  const headlineSize = resolveTierSize(input.headline, headlineTarget, headlineMin, safeWidth);
  const headlineLead = Math.round(headlineSize * (isQuote ? 1.02 : 0.98));

  const kickerY = FRAME_INSET + 70;
  const captionSize = 27;

  // The quote mark used to be a literal font glyph at a huge size — Bebas
  // Neue's punctuation glyphs render far smaller than their cap-height
  // suggests, so it read as a stray mark instead of a bold pull-quote
  // symbol. The headline text itself already carries the literal quotation
  // marks (`"…"`), so the mark was redundant decoration — dropped it and
  // centered the block instead, which is what actually fixes the dead-space
  // problem (point 12: intentional negative space, not a leftover gap).
  const captionLines = input.caption ? wrapText(input.caption, captionSize, safeWidth, BAHN_GLYPH_FACTOR, 2) : [];
  const captionLead = Math.round(captionSize * 1.35);

  const headlineBlockH = (input.headline.length - 1) * headlineLead + headlineSize * 0.92;
  const captionGap = captionLines.length ? 40 + captionSize * 0.8 + (captionLines.length - 1) * captionLead : 0;
  const contentH = headlineBlockH + captionGap;

  const zoneTop = kickerY + 60;
  const zoneBottom = H - FRAME_INSET - 90;
  const blockStartY = zoneTop + Math.max(0, (zoneBottom - zoneTop - contentH) / 2);

  const headlineStartY = blockStartY + headlineSize * 0.73;
  const headlineEndY = headlineStartY + (input.headline.length - 1) * headlineLead;
  const captionStartY = captionLines.length ? headlineEndY + 40 + captionSize * 0.73 : 0;
  const captionEndY = captionLines.length ? captionStartY + (captionLines.length - 1) * captionLead : 0;

  const contentBottom = captionLines.length ? captionEndY : headlineEndY;
  if (contentBottom > zoneBottom + 20) {
    throw new HeadlineOverflowError(input.caption ?? input.headline[input.headline.length - 1], safeWidth);
  }

  const { buf: logoBuf, w: logoW, h: logoH } = await officialLogo();
  const logoX = W - MARGIN_X - logoW;
  const logoY = FRAME_INSET + 28;

  const headlineColor = isQuote ? INK : MAISCAR_RED;
  const headlineSvg = input.headline
    .map((line, i) => `<text x="${textX}" y="${headlineStartY + i * headlineLead}" font-family="Bebas Neue" font-size="${headlineSize}" fill="${headlineColor}" letter-spacing="0.5">${esc(line.toUpperCase())}</text>`)
    .join("\n");

  // Stat mode gets a short red rule under the number — the "editorial
  // accent" the red is supposed to be (point 8), not a filled block.
  const statRuleY = headlineEndY + 26;

  const svg = `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
    <defs>${defsBlock()}</defs>
    <rect width="${W}" height="${H}" fill="${PANEL_BG}" />

    <text x="${textX}" y="${kickerY}" font-family="Bahnschrift SemiBold" font-weight="600" font-size="21" letter-spacing="5" fill="${INK}">${esc(input.kicker.toUpperCase())}</text>
    <line x1="${MARGIN_X}" y1="${kickerY + 14}" x2="${MARGIN_X + 70}" y2="${kickerY + 14}" stroke="${MAISCAR_RED}" stroke-width="3" />

    ${headlineSvg}
    ${!isQuote ? `<line x1="${textX}" y1="${statRuleY}" x2="${textX + 120}" y2="${statRuleY}" stroke="${MAISCAR_RED}" stroke-width="4" />` : ""}
    ${captionLines.map((line, i) => `<text x="${textX}" y="${captionStartY + i * captionLead}" font-family="Bahnschrift SemiBold" font-weight="500" font-size="${captionSize}" fill="${INK}" fill-opacity="0.65">${esc(line)}</text>`).join("\n")}

    ${cornerBrackets()}
    <image href="data:image/png;base64,${logoBuf.toString("base64")}" x="${logoX}" y="${logoY}" width="${logoW}" height="${logoH}" />
    ${folioSvg(input.pageLabel, { color: "#2A2A2A", halo: "#FFFFFF" })}
  </svg>`;

  const base = await sharp({ create: { width: W, height: H, channels: 4, background: PANEL_BG } }).png().toBuffer();
  return sharp(base).composite([{ input: Buffer.from(svg), top: 0, left: 0 }]).png().toBuffer();
}

// ---------------------------------------------------------------------------
// SPLIT — two-column tension/comparison, vertical seam with tech ticks.
// ---------------------------------------------------------------------------

export interface SplitInput {
  family: "split";
  kicker: string;
  left: { label: string; line: string; data?: string };
  right: { label: string; line: string; data?: string };
  takeaway?: string; // one closing line spanning the full width, under the split
  pageLabel?: string;
}

export async function renderSplit(input: SplitInput): Promise<Buffer> {
  assertCleanExport({
    kicker: input.kicker,
    leftLabel: input.left.label,
    leftLine: input.left.line,
    leftData: input.left.data,
    rightLabel: input.right.label,
    rightLine: input.right.line,
    rightData: input.right.data,
    takeaway: input.takeaway,
    pageLabel: input.pageLabel,
  });
  const colW = W / 2 - MARGIN_X - 24;
  const leftX = MARGIN_X;
  const rightX = W - MARGIN_X;

  const lineTarget = 58;
  const lineMin = 42;
  const leftSize = resolveTierSize([input.left.line], lineTarget, lineMin, colW);
  const rightSize = resolveTierSize([input.right.line], lineTarget, lineMin, colW);

  // The comparison block centers in the upper-middle zone, and the takeaway
  // — the verdict — anchors near the bottom margin as its own beat instead
  // of trailing right under the columns. That's what turns the lower half
  // of the canvas into a deliberate pause before the conclusion rather than
  // a leftover gap (point 12).
  const kickerY = FRAME_INSET + 70;
  const blockH = 70 + 56; // label→line + line→data
  const zoneTop = kickerY + 70;
  const takeawayY = H - FRAME_INSET - 130;
  const zoneBottom = takeawayY - 90;
  const labelY = zoneTop + Math.max(0, (zoneBottom - zoneTop - blockH) / 2);
  const lineY = labelY + 70;
  const dataY = lineY + 56;

  const takeawaySize = input.takeaway ? resolveTierSize([input.takeaway], 46, 36, W - MARGIN_X * 2) : 46;
  const dataLead = 31;
  const leftDataLines = input.left.data ? wrapText(input.left.data, 24, colW, BAHN_GLYPH_FACTOR, 2) : [];
  const rightDataLines = input.right.data ? wrapText(input.right.data, 24, colW, BAHN_GLYPH_FACTOR, 2) : [];

  const { buf: logoBuf, w: logoW, h: logoH } = await officialLogo();
  const logoX = W - MARGIN_X - logoW;
  const logoY = FRAME_INSET + 28;

  const seamX = W / 2;
  const seamTop = kickerY - 30;
  const seamBottom = dataY + 40;

  const svg = `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
    <defs>${defsBlock()}</defs>
    <rect width="${W}" height="${H}" fill="${PANEL_BG}" />

    <text x="${leftX}" y="${kickerY}" font-family="Bahnschrift SemiBold" font-weight="600" font-size="21" letter-spacing="5" fill="${INK}">${esc(input.kicker.toUpperCase())}</text>
    <line x1="${MARGIN_X}" y1="${kickerY + 14}" x2="${MARGIN_X + 70}" y2="${kickerY + 14}" stroke="${MAISCAR_RED}" stroke-width="3" />

    <line x1="${seamX}" y1="${seamTop}" x2="${seamX}" y2="${seamBottom}" stroke="${MAISCAR_RED}" stroke-width="2" stroke-opacity="0.6" />
    ${Array.from({ length: 8 }).map((_, i) => `<line x1="${seamX - 8}" y1="${seamTop + (i * (seamBottom - seamTop)) / 7}" x2="${seamX + 8}" y2="${seamTop + (i * (seamBottom - seamTop)) / 7}" stroke="${MAISCAR_RED}" stroke-width="1.5" stroke-opacity="0.5" />`).join("\n")}

    <text x="${leftX}" y="${labelY}" font-family="Bahnschrift SemiBold" font-weight="600" font-size="20" letter-spacing="3" fill="${MAISCAR_RED}">${esc(input.left.label.toUpperCase())}</text>
    <text x="${leftX}" y="${lineY}" font-family="Bebas Neue" font-size="${leftSize}" fill="${INK}" letter-spacing="0.5">${esc(input.left.line.toUpperCase())}</text>
    ${leftDataLines.map((l, i) => `<text x="${leftX}" y="${dataY + i * dataLead}" font-family="Bahnschrift SemiBold" font-weight="500" font-size="24" fill="${INK}" fill-opacity="0.62">${esc(l)}</text>`).join("\n")}

    <text x="${rightX}" y="${labelY}" font-family="Bahnschrift SemiBold" font-weight="600" font-size="20" letter-spacing="3" fill="${MAISCAR_RED}" text-anchor="end">${esc(input.right.label.toUpperCase())}</text>
    <text x="${rightX}" y="${lineY}" font-family="Bebas Neue" font-size="${rightSize}" fill="${INK}" letter-spacing="0.5" text-anchor="end">${esc(input.right.line.toUpperCase())}</text>
    ${rightDataLines.map((l, i) => `<text x="${rightX}" y="${dataY + i * dataLead}" font-family="Bahnschrift SemiBold" font-weight="500" font-size="24" fill="${INK}" fill-opacity="0.62" text-anchor="end">${esc(l)}</text>`).join("\n")}

    ${
      input.takeaway
        ? `<line x1="${leftX}" y1="${takeawayY - takeawaySize - 24}" x2="${rightX}" y2="${takeawayY - takeawaySize - 24}" stroke="${MAISCAR_RED}" stroke-width="1" stroke-opacity="0.35" />
           <text x="${leftX}" y="${takeawayY}" font-family="Bebas Neue" font-size="${takeawaySize}" fill="${MAISCAR_RED}" letter-spacing="0.5">${esc(input.takeaway.toUpperCase())}</text>`
        : ""
    }

    ${cornerBrackets()}
    <image href="data:image/png;base64,${logoBuf.toString("base64")}" x="${logoX}" y="${logoY}" width="${logoW}" height="${logoH}" />
    ${folioSvg(input.pageLabel, { color: "#2A2A2A", halo: "#FFFFFF" })}
  </svg>`;

  const base = await sharp({ create: { width: W, height: H, channels: 4, background: PANEL_BG } }).png().toBuffer();
  return sharp(base).composite([{ input: Buffer.from(svg), top: 0, left: 0 }]).png().toBuffer();
}

// ---------------------------------------------------------------------------
// Dispatcher + legacy alias (renderDiagonalSlideV4 == renderHero, kept so the
// v4 demo script and any earlier caller don't need changes).
// ---------------------------------------------------------------------------

export type SlideInputV4 = HeroInput | EditorialInput | DataInput | SplitInput;

/**
 * Visual Lock (2026-09-03): EDITORIAL/DATA/SPLIT are disabled for
 * production — they allowed photo-less cards and non-diagonal layouts,
 * which is exactly the "seven identities" problem the lock corrects.
 * Their implementations stay in this file only as historical reference /
 * rollback; renderEditorial/renderData/renderSplit are still directly
 * importable if a future, deliberate decision reintroduces them, but the
 * shared dispatcher every production call site uses now refuses them.
 */
export async function renderSlideV4(input: SlideInputV4): Promise<Buffer> {
  const family = (input as any).family ?? "hero";
  if (family !== "hero") {
    throw new VisualIdentityError(
      `família "${family}" está desativada para publicação — a identidade Mais.Car usa exclusivamente o MASTER DIAGONAL (hero). Ver Visual Lock, 2026-09-03.`,
    );
  }
  return renderHero(input as HeroInput);
}

export async function renderSlideV4ToFile(input: SlideInputV4, outPath: string) {
  const buf = await renderSlideV4(input);
  fs.writeFileSync(outPath, buf);
  return outPath;
}

/** @deprecated use renderHero / renderSlideV4 — kept as an alias for the existing demo script. */
export const renderDiagonalSlideV4 = renderHero;
export type DiagonalSlideInputV4 = HeroInput;

export async function renderDiagonalSlideV4ToFile(input: HeroInput, outPath: string) {
  const buf = await renderHero(input);
  fs.writeFileSync(outPath, buf);
  return outPath;
}
